language: python
python:
  - '3.5'
sudo: required
services: postgresql
addons:
  postgresql: "9.4"
env:
    global:
        DB_NAME=lims
        DB_USER=postgres
        SALESFORCE_USERNAME='none'
        SALESFORCE_PASSWORD='none'
        SALESFORCE_TOKEN='none'
        PROJECT_IDENTIFIER_PREFIX='P'
        PROJECT_IDENTIFIER_START=100
before_script:
  - psql -U $DB_USER -c "create database $DB_NAME;"
  - python manage.py migrate
  - python manage.py createinitialrevisions
install: "pip install -r requirements.txt"
script:
  - flake8
  - python manage.py test
