language: python
python: "3.5"
sudo: required
services: postgresql
addons:
  postgresql: "9.4"
env:
    global:
        DB_NAME=lims
        DB_USER=postgres
        SALESFORCE_USERNAME='none'
        SALESFORCE_PASSWORD='none'
        SALESFORCE_TOKEN='none'
        PROJECT_IDENTIFIER_PREFIX='PROJ'
        PROJECT_IDENTIFIER_START=100
before_script:
  - psql -U $DB_USER -c "create database $DB_NAME;"
  - python manage.py migrate
  - echo "from django.contrib.auth.models import User; User.objects.create_superuser('test', 'test@example.com', 'test')" | python manage.py shell
install: "pip install -r requirements.txt"
script: manage.py test
